from enum import Enum
from typing import Callable
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.BaseEventEngine import BaseEventEngine
from codeallybasic.BaseEventEngine import Topic
from codeallybasic.UnitTestBase import UnitTestBase


class UnitTestEventType(Enum):
    UnitTestEvent1 = 'Unit Test Event 1'


class UnitTestEventEngine(BaseEventEngine):

    def __init__(self):
        pass

    def registerListener(self, eventType: UnitTestEventType, callback: Callable):
        self._subscribe(topic=Topic(eventType.value), callback=callback)

    def sendEvent(self, eventType: UnitTestEventType, **kwargs):
        self._sendMessage(topic=Topic(eventType.value), **kwargs)


class TestBaseEventEngine(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 23 July 2025
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

        self._event1ListenerCalled: bool = False

    def tearDown(self):
        super().tearDown()

    def testBasicSubscribe(self):
        eventEngine: UnitTestEventEngine = UnitTestEventEngine()

        eventEngine.registerListener(eventType=UnitTestEventType.UnitTestEvent1, callback=self._event1Listener)

        eventEngine.sendEvent(eventType=UnitTestEventType.UnitTestEvent1)

        self.assertTrue(self._event1ListenerCalled, 'Listener not called')

    def _event1Listener(self):
        self._event1ListenerCalled = True


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestBaseEventEngine))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
