
from typing import List
from typing import cast

from copy import deepcopy


from pathlib import Path

from codeallybasic.ConfigurationLocator import ConfigurationLocator
from codeallybasic.Dimensions import Dimensions
from codeallybasic.DynamicConfiguration import StringList
from codeallybasic.UnitTestBase import UnitTestBase

from codeallybasic.DynamicConfiguration import UnDefinedValueDescription

from unittest import TestSuite
from unittest import main as unitTestMain

from tests.codeallybasic.DynamiteConfigCommonValues import MODULE_NAME
from tests.codeallybasic.DynamiteConfigCommonValues import NO_INTERPOLATION_DEFAULT
from tests.codeallybasic.DynamiteConfigCommonValues import PREFERENCES_FILE_NAME
from tests.codeallybasic.DynamiteConfigCommonValues import STRING_LIST_PROPERTY

from tests.codeallybasic.DynamiteConfiguration import DynamiteConfiguration

from tests.codeallybasic.UnitTestEnumeration import UnitTestEnumeration


class TestDynamicConfiguration(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – HUMBERTO A. Sanchez II
        Generated: 19 October 2024
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

        locator: ConfigurationLocator = ConfigurationLocator()
        self.logger.debug(f'{locator.configurationHome=}')
        prefsPath: Path = locator.applicationPath(applicationName=MODULE_NAME, create=False)
        #
        prefsFile: Path = prefsPath / PREFERENCES_FILE_NAME
        # Save the original in case it exists
        if prefsFile.exists() is True:
            self._savePath: Path = prefsFile.rename(f'{prefsFile}.SAVE')
        else:
            self._savePath = cast(Path, None)

        self._prefsFile: Path = prefsFile

    def tearDown(self):
        super().tearDown()

        # Remove the newly created one
        # put the original back
        if self._savePath is not None:
            self._prefsFile.unlink(missing_ok=True)
            self._savePath.rename(str(self._prefsFile))

    def testNoInterpolation(self):
        dyno:    DynamiteConfiguration = DynamiteConfiguration()

        self.assertEqual(NO_INTERPOLATION_DEFAULT, dyno.noInterpolation, 'Hmm did not pass through')

    def testStrList(self):
        dyno:    DynamiteConfiguration = DynamiteConfiguration()
        strList: List[str]             = dyno.stringList

        self.assertEqual(STRING_LIST_PROPERTY, strList, 'Incorrectly deserialized')

    def testModifyStrList(self):

        dyno:           DynamiteConfiguration = DynamiteConfiguration()
        # noinspection PyTypeChecker
        saveStrList:    StringList             = dyno.stringList
        updatedStrList: StringList             = deepcopy(saveStrList)

        updatedStrList.append('Opie')

        dyno.stringList = updatedStrList
        actualList: StringList = dyno.stringList

        self.assertEqual(updatedStrList, actualList, 'Oops did not update correctly')

        dyno.stringList = saveStrList

    def testBooleanTrue(self):
        dyno: DynamiteConfiguration = DynamiteConfiguration()

        saveValue:     bool = dyno.showInternals
        expectedValue: bool = True
#         dyno.showInternals  = expectedValue

        actualValue:   bool = dyno.showInternals

        dyno.showInternals = saveValue

        self.assertEqual(expectedValue, actualValue, 'Boolean set `True` not working')

    def testDefaultInstantiation(self):
        dyno: DynamiteConfiguration = DynamiteConfiguration()
        self.assertIsNotNone(dyno)

    def testDeserializer(self):
        dyno: DynamiteConfiguration = DynamiteConfiguration()

        noteDimensions: Dimensions = dyno.noteDimensions

        self.assertTrue(isinstance(noteDimensions, Dimensions), 'Incorrect type')

    def testEnumPropertyUsesName(self):
        dyno: DynamiteConfiguration = DynamiteConfiguration()
        dyno.nameEnum = UnitTestEnumeration.FRAN

    def testEnumPropertyUsesNameGet(self):
        dyno: DynamiteConfiguration = DynamiteConfiguration()

        testEnumeration: UnitTestEnumeration = dyno.nameEnum
        self.assertTrue(isinstance(testEnumeration, UnitTestEnumeration), 'Wrong type returned')

    def testEnumPropertyUsesValue(self):
        dyno: DynamiteConfiguration = DynamiteConfiguration()
        dyno.valueEnum = UnitTestEnumeration.OZZEE

    def testEnumPropertyUsesValueGet(self):
        dyno: DynamiteConfiguration = DynamiteConfiguration()
        testEnumeration: UnitTestEnumeration = dyno.valueEnum

        self.assertTrue(isinstance(testEnumeration, UnitTestEnumeration), 'Wrong type returned')

    def testDynamicSet(self):
        dyno: DynamiteConfiguration = DynamiteConfiguration()

        expectedValue: str = 'A new value'
        dyno.noteText = expectedValue

        self.assertEqual(expectedValue, dyno.noteText, 'WTH. the value did not change')

    def testNoValueDescription(self):

        dyno: DynamiteConfiguration = DynamiteConfiguration()

        self.assertRaises(UnDefinedValueDescription, lambda: self._setBadValue(dyno))

    def _setBadValue(self, dyno: DynamiteConfiguration):
        dyno.bogusKey = 'I am bogus'        # type: ignore


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestDynamicConfiguration))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
