
from functools import wraps

from unittest import TestSuite
from unittest import main as unitTestMain

from unittest.mock import Mock


from codeallybasic.BasePubSubEngine import BasePubSubEngine
from codeallybasic.BasePubSubEngine import MessageListener
from codeallybasic.BasePubSubEngine import Topic
from codeallybasic.UnitTestBase import UnitTestBase


class PubSubEngine(BasePubSubEngine):

    def __init__(self):
        super().__init__()

    def subscribe(self, topic: Topic, listener: MessageListener):
        self._subscribe(topic=topic, listener=listener)

    def sendMessage(self, topic: Topic, **kwargs):
        self._sendMessage(topic=topic, **kwargs)


OZZEE_TOPIC: Topic = Topic('OzzeeTopic')


def checkCalled(func):

    @wraps(func)
    def wrapper(*args, **kwargs):
        result = Mock(*args, **kwargs)  # parameter 'func' comes in via args or kwargs
        return result
    return wrapper

def check_called(func):
    return Mock(side_effect=func)

@check_called
def ozzeeTopicListener():
    print('I have been called!')


class TestBasePubSubEngine(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 02 September 2025
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

        self._withArgumentCalled: bool = False

    def tearDown(self):
        super().tearDown()

    def testBasicSubscription(self):
        pubSub: PubSubEngine = PubSubEngine()

        pubSub.subscribe(topic=OZZEE_TOPIC, listener=ozzeeTopicListener)

        pubSub.sendMessage(topic=OZZEE_TOPIC)

        self.assertTrue(ozzeeTopicListener.called, 'Whoa, I was not called')

    def testSubscriptionWithArgument(self):
        pubSub: PubSubEngine = PubSubEngine()

        pubSub.subscribe(topic=OZZEE_TOPIC, listener=self._ozzeeTopicListenerWithArgument)

        pubSub.sendMessage(topic=OZZEE_TOPIC, catNip='tasty treats')

        self.assertTrue(self._withArgumentCalled, 'Whoa, I was not called')

    def _ozzeeTopicListenerWithArgument(self, catNip: str):
        print(f'Meow, I like {catNip}')
        self._withArgumentCalled = True


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestBasePubSubEngine))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
