
import shutil

from pathlib import Path

from tempfile import gettempdir
from typing import cast

from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.Basic import Basic
from codeallybasic.Basic import RunResult
#
# from codeallybasic.Common import cmp
from codeallybasic.UnitTestBase import UnitTestBase


API_URL:   str = 'https://api.github.com/repos/hasii2011/code-ally-advanced'
FIXED_URL: str = 'https://github.com/hasii2011/code-ally-advanced'


class TestBasic(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 02 February 2025
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testFixUrl(self):
        actualUrl: str = Basic.fixURL(oldURL=API_URL)

        self.assertEqual(FIXED_URL, actualUrl, 'Fix did not work')

    def testGoodRun(self):
        basicLsCommand: str = 'ls'
        execPath: str | None = shutil.which(basicLsCommand)

        runResult: RunResult = Basic.runCommand(programToRun=cast(str, execPath))

        self.assertEqual(0, runResult.returnCode)

    def testBadRun(self):
        runResult: RunResult = Basic.runCommand(programToRun='bogus')

        self.assertNotEqual(0, runResult.returnCode)

    def testDeleteDirectory(self):

        tmpDir = gettempdir()
        tmpProjectsBase: Path = Path(tmpDir) / 'bogusDirectoryToDelete' / 'EvenDeeperDirectory'
        tmpProjectsBase.mkdir(exist_ok=True)

        Basic.deleteDirectory(tmpProjectsBase)

        exists: bool = tmpProjectsBase.exists()

        self.assertFalse(exists, 'Oops deep directory not deleted')

    # def testDeprecated(self):
    #
    #     value = cmp(1, 3)
    #     print(value)


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestBasic))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
